// INITIAL ACTION TYPE

export const INITIAL_ACTION = "INITIAL_ACTION";

// LOGIN USER ACTION TYPES
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER_IN_PROGRESS = "LOGIN_USER_IN_PROGRESS";
